const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      primary: colors.blueGray,
      secondary: colors.amber,
      success: colors.emerald,
      blueGray: colors.blueGray,
      amber: colors.amber,
      emerald: colors.emerald,
      teal: colors.teal,
      blue: colors.blue,
      red: colors.red,
      green: colors.green,
      black: colors.black,
      gray: colors.gray,
      grey: colors.gray,
      white: colors.white,
      cool: colors.coolGray
    },
    fontSize: {
      '3xs': '.5rem',
      '2xs': '.65rem',
      'xs': '.75rem',
      'sm': '.875rem',
      'base': '1rem',
      'lg': '1.125rem',
      'xl': '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    fontFamily: {
      'sans': ['Poppins', 'system-ui', 'sans-serif'],
      'serif': ['ui-serif', 'Georgia', "serif"],
      'mono': ['ui-monospace', 'SFMono-Regular', "monospace"],
    },
    container: {
      center: true,
    },
    extend: {
      height: {
        '104': '25rem',
        '120': '26rem',
        '136': '27rem',
        '150': '28rem',
        'half-screen': '50vh',
        '1/4-screen': '25vh',
        '3/4-screen': '75vh'
      },
      minHeight: {
        '1/2': '50%',
        '1/3': '33.33333%',
        '2/3': '66.66666%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
      },
      width: {
        '104': '25rem',
        '120': '26rem',
        '136': '27rem',
        '150': '28rem',
        'half-screen': '50vw',
        '1/4-screen': '25vw',
        '3/4-screen': '75vw'
      },
      gridTemplateRows: {
        '8': 'repeat(8, minmax(0, 1fr))',
        '9': 'repeat(9, minmax(0, 1fr))',
        '10': 'repeat(10, minmax(0, 1fr))',
        '12': 'repeat(12 minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      gridRow: {
        'span-8': 'span 8 / span 8',
        'span-9': 'span 9 / span 9',
        'span-10': 'span 10 / span 10',
        'span-11': 'span 11 / span 11',
        'span-12': 'span 12 / span 12',
      },
      gridRowStart: {
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
      },
      gridRowEnd: {
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
      },
      gridTemplateColumns: {
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      gridColumn: {
        'span-16': 'span 16 / span 16',
      },
      gridColumnStart: {
        "13": "13",
        "14": "14",
        "15": "15",
        "16": "16",
        "17": "17",
      },
      gridColumnEnd: {
        "13": "13",
        "14": "14",
        "15": "15",
        "16": "16",
        "17": "17",
      },
      zIndex: {
        '25': '25',
        '60': '60',
        '70': '70',
        '75': '75',
        '80': '80',
        '90': '90',
        '100': '100',
        '-10': '-10',
        '-25': '-25',
        '-50': '-50',
        '-75': '-75',
        '-100': '-100',
        'head': '999',
        'after-head': '1000',
        'after-head-1': '1100',
        'after-head-2': '1200',
        'after-head-3': '1300',
        'before-head': '998',
        'before-head-1': '800',
        'before-head-2': '700',
        'before-head-3': '800',
      },
      scale: {
        '99': '.95',
        '101': '1,01'
      },
    },
  },
  variants: {
    extend: {
      animation: ['responsive', 'hover', 'focus', 'active'],
      rotate: ['responsive', 'hover', 'focus', 'active'],
      translate: ['responsive', 'hover', 'focus', 'active'],
      skew: ['responsive', 'hover', 'focus', 'active'],
      scale: ['responsive', 'hover', 'focus', 'active'],
      backgroundColor: ['responsive', 'hover', 'focus', 'active'],
      borderColor: ['responsive', 'hover', 'focus', 'active'],
      boxShadow: ['responsive', 'hover', 'focus', 'active'],
    },
  },
  plugins: [
  ],
}
